[[FIX]] ServerError to be BC with node8 (#18)
V8 shipped with node8 break our test and reported a `this.name` inside
a ServerError instantiation, resulting in setting the name for a
NotFoundError to something like `NotFound.Error`

More info

```
  1) Therror when using ServerError should have precreated classes for statusCodes:

      AssertionError: expected { Object (error, message) } to deeply equal { Object (error, message) }
      + expected - actual

       {
      -  "error": "NotFound.Error"
      +  "error": "NotFound"
         "message": "The user Sarah does not exists"
       }

      at Context.<anonymous> (test/therror.spec.js:584:37)

  2) Therror when using ServerError should hide information to the client:

      AssertionError: expected 'ServiceUnavailable.Error' to deeply equal 'ServiceUnavailable'
      + expected - actual

      -ServiceUnavailable.Error
      +ServiceUnavailable

      at Context.<anonymous> (test/therror.spec.js:603:30)

  3) Therror when using ServerError should set string as message for ServerError:

      AssertionError: expected 'ServiceUnavailable.Error' to deeply equal 'ServiceUnavailable'
      + expected - actual

      -ServiceUnavailable.Error
      +ServiceUnavailable

      at Context.<anonymous> (test/therror.spec.js:616:30)

  4) Therror when using ServerError should set string as cause for ServerError:

      AssertionError: expected 'ServiceUnavailable.Error' to deeply equal 'ServiceUnavailable'
      + expected - actual

      -ServiceUnavailable.Error
      +ServiceUnavailable

      at Context.<anonymous> (test/therror.spec.js:629:30)

  5) Therror when using ServerError should set Number as message for ServerError:

      AssertionError: expected 'ServiceUnavailable.Error' to deeply equal 'ServiceUnavailable'
      + expected - actual

      -ServiceUnavailable.Error
      +ServiceUnavailable

      at Context.<anonymous> (test/therror.spec.js:643:30)

  6) Therror when using ServerError should set Number as cause for ServerError:

      AssertionError: expected 'ServiceUnavailable.Error' to deeply equal 'ServiceUnavailable'
      + expected - actual

      -ServiceUnavailable.Error
      +ServiceUnavailable

      at Context.<anonymous> (test/therror.spec.js:656:30)

```

Closes #16